// JS
// BaseAudioContext
// DOM
// ES6 FEATURES,
// 7 CONCEPTS
// 1 ARROW FUNCTION
// 2. MAP() & FILTER()
// 3. SLICE() & SPLICE()
// 4. PROMISES & ASYNC/AWAIT
// 5. TEMPLATE LITERALS
// 6. SPREAD AND REST PARAMETERS
// 7. DESTRUCTURING ASSIGNMENT

